name: Build and upload

on:
  pull_request:
  push:
    tags:
    - v*
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Build sdist
      run: pipx run build --sdist

    - name: Install from sdist
      run: pip install dist/pyvista_stl*.tar.gz

    - name: Run tests
      run: |
        pip install pyvista pytest
        pytest -x

    - uses: actions/upload-artifact@v4
      with:
        name: pyvista-stl-sdist
        path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [build_sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-15-intel]

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: pyvista-stl-sdist
        path: sdist

    - name: Extract sdist
      shell: bash
      run: |
        mkdir -p src-from-sdist
        tar -xzf sdist/pyvista_stl-*.tar.gz -C src-from-sdist --strip-components=1

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.3.0
      with:
        package-dir: src-from-sdist

    - uses: actions/upload-artifact@v4
      with:
        name: pyvista-stl-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/p/pyvista-stl
    permissions:
      id-token: write  # OIDC trusted publishing
      contents: write  # required to create a release
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
        pattern: pyvista-stl-*

    - run: ls -alR dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          ./dist/*.whl
          ./dist/*.tar.gz
